AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  S3BucketPrefix:
    Type: String
    Default: binxio-public

Resources:
  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: cfn-ami-provider
      Description: 'cfn-ami-provider builder'
      ServiceRole: !Ref 'ProjectRole'
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: LAMBDA_BUCKET_PREFIX
            Value: !Ref S3BucketPrefix
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        Location: https://github.com/binxio/cfn-ami-provider.git
        BuildSpec: .buildspec.yaml
        GitCloneDepth: 0

  ProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
            Condition: {}
      Path: /
      Policies:
        - PolicyName: CFNAMIProviderBuilder
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListObjects
                  - s3:GetBucketLocation
                Resource: 
                  - !Sub 'arn:aws:s3:::${S3BucketPrefix}-*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: 
                  - !Sub 'arn:aws:s3:::${S3BucketPrefix}-*/lambdas/cfn-ami-provider-*'
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:DescribeInstanceStatus
                Resource: 
                  - '*'
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - '*'
